window.SALE_ITEMS = [
  {
    "id": 1,
    "name": "TV LG 65\" OLED",
    "category": "Electronics",
    "brandModel": "",
    "condition": "Very Good",
    "age": "6",
    "price": 750.0,
    "location": "Living Room",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Premium LG OLED display with excellent picture quality, Works perfectly, no issues, Includes remote, Minor signs of use, Great for movies and gaming",
    "photo1": "OLED TV 1.jpg",
    "photo2": "OLED TV 2.jpg",
    "photo3": ""
  },
  {
    "id": 2,
    "name": "Brother Printer (MFCL2700W)",
    "category": "Electronics",
    "brandModel": "",
    "condition": "Very Good",
    "age": "5",
    "price": 200.0,
    "location": "Bedroom 4",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Brother all-in-one laser printer (print/scan/copy), Reliable and fast printing, Works well, no known issues, Ideal for home office or student use, Toner-efficient compared to ink printers",
    "photo1": "Brother_Printer.jpeg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 3,
    "name": "Canon Pixma color printer (MG2525)",
    "category": "Electronics",
    "brandModel": "",
    "condition": "Very Good",
    "age": "4",
    "price": 50.0,
    "location": "Bedroom 4",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Compact Canon inkjet printer, Good for basic home printing needs, Works fine, normal wear, Lightweight and easy to set up, Great as a backup or student printer",
    "photo1": "Canon_Printer.jpeg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 4,
    "name": "Klipsch Sound Bar with Subwoofer",
    "category": "Electronics",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": 250.0,
    "location": "Living Room",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "Klipsch Sound Bar with Subwoofer.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 5,
    "name": "King Bed",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "10+",
    "price": 200.0,
    "location": "Master Bedroom",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Solid wood king-size bed frame, Elegant design with sturdy construction, Good overall condition, Minor wear consistent with use, Mattress and box springs included",
    "photo1": "King Bed.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 6,
    "name": "Queen Bed",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "10+",
    "price": 150.0,
    "location": "Bedroom 2",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Classic design with carved headboard, Solid and durable construction, Good condition overall, Minor cosmetic wear, Mattress and box springs included",
    "photo1": "Queen Bed.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 7,
    "name": "3 seater recliner",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "10+",
    "price": 250.0,
    "location": "Living Room",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Reclining mechanism works smoothly/Synthetic leather peeling; couch is structurally sound. Suitable for a reupholstery project or garage/basement use.",
    "photo1": "Three_Seat_Recliner.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 8,
    "name": "Love seat recliner",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "10+",
    "price": 200.0,
    "location": "Living Room",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Reclining mechanism works smoothly/Synthetic leather peeling; couch is structurally sound. Suitable for a reupholstery project or garage/basement use.",
    "photo1": "Love_Seat_Recliner.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 9,
    "name": "Big bad couch",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Fair",
    "age": "10+",
    "price": 100.0,
    "location": "Living Room",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Synthetic leather peeling; couch is structurally sound. Suitable for a reupholstery project or garage/basement use.",
    "photo1": "Big_Bad_Couch.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 10,
    "name": "Dining table",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Very Good",
    "age": "10+",
    "price": 250.0,
    "location": "Kitchen",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "6 seater, solid wood, recently revarnished",
    "photo1": "Dining_Table_1.jpg",
    "photo2": "Dining_Table2.jpg",
    "photo3": ""
  },
  {
    "id": 11,
    "name": "Entertainment center",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "10+",
    "price": 300.0,
    "location": "Kitchen",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Large solid wood entertainment center, Multiple shelves and storage cabinets, Good structural condition, Minor cosmetic wear, Ideal for large living rooms",
    "photo1": "Entertainment_Center.png",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 12,
    "name": "TV stand",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Very Good",
    "age": "2",
    "price": 50.0,
    "location": "Living Room",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "TV_Stand.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 13,
    "name": "Recliner",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Very Good",
    "age": "2",
    "price": 100.0,
    "location": "Bedroom 3",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "Recliner.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 14,
    "name": "Playroom table and chair set",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": 50.0,
    "location": "Bedroom 4",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 15,
    "name": "Office chair",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Like New",
    "age": "<1",
    "price": 100.0,
    "location": "Bedroom 4",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "Office_Chair.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 16,
    "name": "Chest Drawer 1",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": 50.0,
    "location": "Master Bedroom",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "Chest Drawer1.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 17,
    "name": "Chest Drawer 2",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": 50.0,
    "location": "Bedroom 3",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "Chest Drawer2.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 18,
    "name": "Chest Drawer 3",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": 25.0,
    "location": "Bedroom 4",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Has some water damage at the base and surface",
    "photo1": "Chest Drawer3.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 19,
    "name": "Side table 1",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Very Good",
    "age": "",
    "price": 100.0,
    "location": "Bedroom 2",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "Side_Table1.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 20,
    "name": "Side table 2",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Very Good",
    "age": "",
    "price": 100.0,
    "location": "Bedroom 2",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "Side_Table2.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 21,
    "name": "Patio Umbrella",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Very Good",
    "age": "5+",
    "price": 50.0,
    "location": "",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Outdoor patio umbrella with weighted base, Includes protective cover, Good structural condition, Normal wear from outdoor use, Ready for immediate use",
    "photo1": "Patio Umbrella.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 22,
    "name": "Coffee Table",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Like New",
    "age": "1",
    "price": 60.0,
    "location": "",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Modern glass-top coffee table with metal base, Sturdy and stable construction, Minor wear consistent with normal use, Clean, minimalist design, Easy to match with most interiors",
    "photo1": "Coffee_Table.jpg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 23,
    "name": "Tempurpedic Mattress Topper King Size",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Very Good",
    "age": "3",
    "price": 100.0,
    "location": "",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "High-quality Tempurpedic memory foam toppers, Lightly used and in good condition, No stains or damage, Adds significant comfort to any mattress",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 24,
    "name": "Tempurpedic Mattress Topper Queen Size",
    "category": "Furniture",
    "brandModel": "",
    "condition": "Very Good",
    "age": "3",
    "price": 75.0,
    "location": "",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "High-quality Tempurpedic memory foam toppers, Lightly used and in good condition, No stains or damage, Adds significant comfort to any mattress",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 25,
    "name": "Honda Mower",
    "category": "Garage / Tools",
    "brandModel": "",
    "condition": "Good",
    "age": "10+",
    "price": 75.0,
    "location": "Garrage",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Pending",
    "notes": "",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 26,
    "name": "Blower (chorded)",
    "category": "Garage / Tools",
    "brandModel": "",
    "condition": "Good",
    "age": "10+",
    "price": 25.0,
    "location": "Garrage",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Pending",
    "notes": "",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 27,
    "name": "Shop vacuum",
    "category": "Garage / Tools",
    "brandModel": "",
    "condition": "Good",
    "age": "10+",
    "price": 50.0,
    "location": "Garrage",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Pending",
    "notes": "",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 28,
    "name": "Leaf vacuum",
    "category": "Garage / Tools",
    "brandModel": "",
    "condition": "Good",
    "age": "8",
    "price": 50.0,
    "location": "Garrage",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Pending",
    "notes": "",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 29,
    "name": "Outside two chair and table set",
    "category": "Home & Kitchen",
    "brandModel": "",
    "condition": "Very Good",
    "age": "5+",
    "price": 100.0,
    "location": "",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Decorative outdoor bistro-style table with 2 chairs, Metal construction with elegant design, Good structural condition, Minor wear from outdoor use, Perfect for patio, balcony, or garden seating",
    "photo1": "Outside two chair and table set.jpeg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 30,
    "name": "Bike 1",
    "category": "Kids",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": null,
    "location": "Garrage",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 31,
    "name": "Bike 2",
    "category": "Kids",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": null,
    "location": "Garrage",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 32,
    "name": "Bike 3",
    "category": "Kids",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": null,
    "location": "Garrage",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 33,
    "name": "Carpet Round",
    "category": "Miscellaneous",
    "brandModel": "",
    "condition": "Good",
    "age": "",
    "price": 100.0,
    "location": "Bedroom 4",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Colorful round area rug with unique pattern, Adds character to any room, Some signs of use (see photo),Still functional and visually appealing, Good for bedroom or kids’ room",
    "photo1": "Round_Carpet.jpeg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 34,
    "name": "Carpet Square",
    "category": "Miscellaneous",
    "brandModel": "",
    "condition": "Very Good",
    "age": "",
    "price": 75.0,
    "location": "Living Room",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "Bright multicolor square rug, Modern geometric design, Good condition overall, Adds a vibrant touch to living spaces, Suitable for playroom or living room",
    "photo1": "Square_Carpet.jpeg",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 35,
    "name": "Honda Pilot 2019 Touring",
    "category": "Transport",
    "brandModel": "",
    "condition": "Very Good",
    "age": "7",
    "price": 28000.0,
    "location": "",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Pending",
    "notes": "25000 miles, Price based in KBB.",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  },
  {
    "id": 36,
    "name": "Toyota Rav 4 Limited Edition 2018",
    "category": "Transport",
    "brandModel": "",
    "condition": "Very Good",
    "age": "8",
    "price": 25000,
    "location": "",
    "pickupWindow": "",
    "bundleEligible": "",
    "status": "Available",
    "notes": "45000 miles, Price based on KBB.",
    "photo1": "",
    "photo2": "",
    "photo3": ""
  }
];
